### ISSUE TITLE
Client IP is only IP of node the pod is running on and assigning a new IP from metallb

### ISSUE THREAD

**Issue by paulmorabito** [MoJo2600/pihole-kubernetes#3] opened 2019-03-04 12:42 UTC
Hi,

Thanks for providing these configs. It's a great help.

I have everything up and running but am noticing that the Client IP is the IP of the node in the cluster that the pod is running on. I definitely have spec.externalTrafficPolicy set to Local.

My Kubernetes versions are below:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

I'm using Rancher 2.1.6 and Metallb also for the load balancing.

I also have noticed that if I assign an IP to the node and then restart the node, I can't connect to it using the same P (even if i remove and re-add the service). The only way to get it working again is to assign a new IP to the service.

Any ideas on how to debug this further?

**Comment by MoJo2600** [comment] 2019-03-06 12:38
Hello!

Ok, can you post your configuration? I'd like to have a look at it.

Which version of metallb are you using. There is a known [bug](https://github.com/google/metallb/issues/335#event-2172727406) in version 0.7.3 where you have to restart the speaker pods to get metallb to announce the ips again. You can either downgrade to 0.7.2 or wait for release 0.7.4 to get rid of this behaviour.

Best!

**Comment by paulmorabito** [comment] 2019-03-07 11:45
Thanks for pointing out the metallb issue. I reverted to 0.7.2 and it works fine now.

I've pasted the deployment config below. Actually, I have two entries:

* the node that the pod is running on.
* kube-dns-ddddcfcc8-p72zk which I guess is the cluster kube-dns resolving internal dns queries?

The config itself is much like your original.

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: services
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: ServerIP
          value: 192.168.1.243
        - name: WEBPASSWORD
          value: xxx
        - name: TZ
         value: Asia/Seoul
        image: pihole/pihole
        imagePullPolicy: Always
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-ssl
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
     dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
status: {}

--

**Comment by MoJo2600** [comment] 2019-03-19 18:37
Can you post the configuration of the services as well? Sorry for the delay. Been pretty busy :D

**Comment by paulmorabito** [comment] 2019-03-20 00:12
Sure, no worries. Here you go:

'''

apiVersion: v1

kind: Service

metadata:

  annotations:

    metallb.universe.tf/allow-shared-ip: pihole-svc

  labels:

    app: pihole

  name: pihole-tcp

  namespace: apps

spec:

  externalTrafficPolicy: Local

  loadBalancerIP: 192.168.1.243

  ports:

  - name: pihole-http

    port: 80

    protocol: TCP

    targetPort: pihole-http

  - name: pihole-https

    port: 443

    protocol: TCP

    targetPort: pihole-https

  - name: dns

    port: 53

    protocol: TCP

    targetPort: dns

  selector:

    app: pihole

  sessionAffinity: None

  type: LoadBalancer

'''


and


'''

apiVersion: v1

kind: Service

metadata:

  annotations:

    metallb.universe.tf/allow-shared-ip: pihole-svc

  labels:

    app: pihole

  name: pihole-udp

  namespace: apps

spec:

  externalTrafficPolicy: Local

  loadBalancerIP: 192.168.1.243

  ports:

  - name: dns-udp

    port: 53

    protocol: UDP

    targetPort: dns-udp

  - name: client-udp

    port: 67

    protocol: UDP

    targetPort: client-udp

  selector:

    app: pihole

  sessionAffinity: None

  type: LoadBalancer

'''

**Comment by MoJo2600** [comment] 2019-04-08 09:03
I recently merged my helm chart branch to master. Would you please try to deploy everything with the helm chart and the documentation i provided. I tried it multiple times and everything was working right out of the box.

**Comment by paulmorabito** [comment] 2019-04-16 07:41
Sorry for the late reply.

I've downloaded the Chart.yml and values.yaml. I'm getting an error trying
to install the chart:

helm upgrade -i pihole --namespace apps ./Chart.yaml -f values.yaml
Release "pihole" does not exist. Installing it now.
Error: gzip: invalid header

Ay ideas?

**Comment by MoJo2600** [comment] 2019-04-16 08:30
Your helm command is wrong. You have to point to the chart directory, not the Chart.yaml. The error is absolutely misleading.

`helm upgrade -i pihole --namespace apps ./pihole -f values.yaml`

**Comment by paulmorabito** [comment] 2019-04-16 09:59
That worked. Thanks.

I also tested and I can see individual IP addresses now.  So, all good.

One question on the version tag. Can I change this to latest or if not, how
do you recommend upgrading? I'm a little new to helm charts.

**Comment by MoJo2600** [comment] 2019-04-16 11:08
Of course you can update the version tag to your liking. I set it to the latest that was available at the time i created the chart. You could even replace the version with 'latest' then you should get always the latest and greatest after repeating the `helm upgrade` command.

**Comment by paulmorabito** [comment] 2019-04-16 11:41
That also works. Thank you so much for your help.

**Comment by MoJo2600** [comment] 2019-04-16 12:02
You are very welcome. Just come back if you have any other questions. I'll close this issue for now.

**Closed by MoJo2600** 2019-04-16 12:02 UTC

**Comment by Ymac101** [comment] 2020-09-25 13:20
Hi there, I am also experiencing this problem, and nothing seems to solve it.
I am quite a noob to kubernetes, but I think I got the hang of it mostly,  I'm pulling my hairs already, I'm on this for the last week.
k3s info:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

metallb v0.9.3 (no easy way to query it! got it out of `edit deployment -n metallb-system`)
I can post more info if it can be of help.

Thank you for  creating this repo! :)

**Comment by MoJo2600** [comment] 2020-09-28 07:43
Could you please elaborate a bit more? I'm not sure I understand what the problem is.

**Comment by Ymac101** [comment] 2020-09-28 12:43
> 
> 
> Could you please elaborate a bit more? I'm not sure I understand what the problem is.

Hi, sorry if I wan't clear.
I'm experiencing the same issue the original poster of this issue, my pihole instance fails to see client's IP's - all traffic seems to come from the host, and it kinda kills the point of pihole when there's no client visibility.
I tried messing with metallb and using it in BGP instead of L2 mode, but it didn't seem to make a difference.
Of course I'm using `spec.externalTrafficPolicy: Local` in the service defenition.
Honestly I kinda giving up and wanting to just spin up a debian VM...

**Comment by snp-g** [comment] 2022-09-06 14:44
> > Could you please elaborate a bit more? I'm not sure I understand what the problem is.
> 
> Hi, sorry if I wasn't clear. I'm experiencing the same issue the original poster of this issue, my pihole instance fails to see client's IP's - all traffic seems to come from the host, and it kinda kills the point of pihole when there's no client visibility. I tried messing with metallb and using it in BGP instead of L2 mode, but it didn't seem to make a difference. Of course I'm using `spec.externalTrafficPolicy: Local` in the service defenition. Honestly I kinda giving up and wanting to just spin up a debian VM...

Hi, have you resolved it, please?
