### ISSUE TITLE
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory

### ISSUE THREAD

**Issue by plsnotracking** [MoJo2600/pihole-kubernetes#69] opened 2020-08-13 05:49 UTC
So, the pihole seems to have started up all right but as I was going through the logs:
```
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
```

Is there something that I missed that maybe should've worked?

Also another question, how do I setup DoH?

I was following this - https://kauri.io/68-selfhost-pihole-on-kubernetes-and-block-ads-and/5268e3daace249aba7db0597b47591ef/a and they seem to have not explained that, is there any place I can read on how to configure DoH? Thank you.

**Comment by 11jwolfe2** [comment] 2020-09-29 13:46
This happens for me as well. I used that same tutorial to set up my cluster. If you are using a persistent volume as well, use a ssh connection to get to your drive and run these two commands.
`ls -l`   ----> this will show the owner and user of each file they all should be www-data if not run this cmd
`sudo chown -R www-data:www-data pihole` from the /mnt/ssd directory described in the tutorial. This will allow you to add more whitelists/blacklists/adlists from the web portal.

**Comment by plsnotracking** [comment] 2020-09-30 23:05
Seems like I still get the error:

```
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
```

What I did was, as you suggested, unless I missed something.

- `ssh` onto my pi.
- `cd` to the pi-hole folder within `/mnt/ssd`
- run `sudo chown -R www-data:www-data pihole` from the outside.
- Output
```
ls -al ~/mnt/ssd/pihole

total 123800
drwxrwxr-x 4        999 spi             4096 Oct  1 00:01 .
drwxr-xr-x 8 pi pi      4096 Sep 16 03:23 ..
-rw-r--r-- 1 www-data   www-data         118 Aug 15 22:50 adlists.list
drwxrwxr-x 3 pi spi             4096 Sep 30 23:54 backup
-rw-r--r-- 1        999 spi             1681 Aug 16 06:02 dhcp.leases
-rw-r--r-- 1 www-data   www-data         596 Sep 30 23:58 dns-servers.conf
-rw-r--r-- 1 www-data   www-data          18 Sep 30 23:58 GitHubVersions
-rw-rw-r-- 1        999 spi          5029888 Sep 30 23:58 gravity.db
-rw-r--r-- 1 www-data   www-data     1131655 Sep 30 23:58 list.0.raw.githubusercontent.com.domains
-rw-r--r-- 1 www-data   www-data      594616 Aug 15 22:09 list.1.mirror1.malwaredomains.com.domains
-rw-r--r-- 1 www-data   www-data          20 Oct  1 00:00 localbranches
-rw-r--r-- 1 www-data   www-data          41 Sep 30 23:58 local.list
-rw-r--r-- 1 www-data   www-data          41 Oct  1 00:00 localversions
drwxr-xr-x 2 www-data   www-data        4096 Aug 15 22:09 migration_backup
-rw-r--r-- 1        999 spi                0 Aug 15 22:09 pihole-FTL.conf
-rw-r--r-- 1 root       root       119951360 Oct  1 00:01 pihole-FTL.db
-rwxr-xr-x 1 www-data   www-data           0 Aug 15 22:09 regex.list
-rw-r--r-- 1 www-data   www-data         717 Sep 30 23:58 setupVars.conf
-rw-r--r-- 1 www-data   www-data         717 Sep 30 23:58 setupVars.conf.update.bak
```

Thanks @11jwolfe2

**Comment by MoJo2600** [comment] 2020-10-14 06:12
Does it possibly be the same issue that has been resolved in this issue: #39 Just guessing, as I do not know your exact setup.

**Comment by MoJo2600** [comment] 2021-01-13 10:33
#107

**Comment by elcid2012** [comment] 2021-01-26 13:28
@MoJo2600 I'm getting this error in the logs on a fresh Docker installation, although everything seems to be working. That is, I just tested adding a domain to the whitelist without issues.

Incidentally, I just checked the logs of my existing Pi-Hole that's been running for months, also Docker, and it's showing the same error.

I am not using the DHCP server feature on either Pi-Hole, so perhaps that's why the error is getting thrown while everything else seems to work correctly?

**Comment by MoJo2600** [comment] 2021-01-28 19:35
Ok, I'll have to check if I can reproduce this error

**Comment by Roelski** [comment] 2021-01-31 21:22
> This happens for me as well. I used that same tutorial to set up my cluster. If you are using a persistent volume as well, use a ssh connection to get to your drive and run these two commands.
> `ls -l` ----> this will show the owner and user of each file they all should be www-data if not run this cmd
> `sudo chown -R www-data:www-data pihole` from the /mnt/ssd directory described in the tutorial. This will allow you to add more whitelists/blacklists/adlists from the web portal.

Is used this to get it running for me. thanx!
Running a shell inside the pihole docker container.
With ls -l /etc/pihole there were different permissions. Some root, some pihole.
Used:
cd /etc
sudo chown -R www-data:www-data pihole

All done inside the container.
Hope this helps others.

**Closed** 2021-09-23 05:58 UTC
